apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
        - name: flipkart-container
          image: your-dockerhub/flipkart:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-service
spec:
  type: LoadBalancer
  selector:
    app: flipkart
  ports:
    - port: 80
      targetPort: 80
